[workspace]
members = [
    "bin",
    "interpreter",
    "parser",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Bjarke Bondo Andersen"]

[workspace.dependencies]
interpreter = { path = "interpreter" }
parser = { path = "parser" }
thiserror = "1.0.44"
