[package]
name = "parser"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
parser-common.workspace = true
parser-macro.workspace = true
thiserror = "1.0.44"
tree-sitter.workspace = true
tree-sitter-swift = "0.3.6"
