[package]
name = "parser"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
colored = "2.0.4"
thiserror = "1.0.44"
tree-sitter = "0.20.10"
tree-sitter-swift = "0.3.6"
